### ISSUE TITLE
Failed to build on io.js@1.0.2

### ISSUE THREAD

**Issue by redism** [isaacs/node-srand#5]
Attaching node-gyp error log

```
> srand@1.1.4 install /Users/redism/dev/sandbox/node-srand
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
2015-01-17 11:28:11.754 xcodebuild[56303:1007] [MT] PluginLoading: Required plug-in compatibility UUID C4A681B0-4A26-480E-93EC-1218098B9AA0 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/srand/srand.o
../srand.cc:9:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> Random (const Arguments&);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/redism/.node-gyp/1.0.2/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../srand.cc:10:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> Rand (const Arguments&);
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/redism/.node-gyp/1.0.2/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../srand.cc:11:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> SRand (const Arguments&);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/redism/.node-gyp/1.0.2/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../srand.cc:14:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> Random (const Arguments& args) {
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/redism/.node-gyp/1.0.2/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../srand.cc:15:51: error: too few arguments to function call, expected 2, have 1
  return Number::New(rand()/((double)RAND_MAX + 1));
         ~~~~~~~~~~~                              ^
/Users/redism/.node-gyp/1.0.2/deps/v8/include/v8.h:2291:3: note: 'New' declared here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../srand.cc:18:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> Rand (const Arguments& args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/redism/.node-gyp/1.0.2/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../srand.cc:19:29: error: too few arguments to function call, expected 2, have 1
  return Integer::New(rand());
         ~~~~~~~~~~~~       ^
/Users/redism/.node-gyp/1.0.2/deps/v8/include/v8.h:2304:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../srand.cc:22:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> SRand (const Arguments& args) {
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/redism/.node-gyp/1.0.2/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../srand.cc:23:11: error: member access into incomplete type 'const v8::internal::Arguments'
  if (args.Length() == 0) {
          ^
/Users/redism/.node-gyp/1.0.2/deps/v8/include/v8.h:133:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../srand.cc:24:52: error: no member named 'New' in 'v8::String'
    return ThrowException(Exception::Error(String::New("Usage: srand(n)")));
                                           ~~~~~~~~^
../srand.cc:26:13: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  srand(args[0]->Uint32Value());
        ~~~~^~
../srand.cc:27:10: error: no matching function for call to 'Undefined'
  return Undefined();
         ^~~~~~~~~
/Users/redism/.node-gyp/1.0.2/deps/v8/include/v8.h:323:28: note: candidate function not viable: requires single argument
      'isolate', but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../srand.cc:31:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/redism/.node-gyp/1.0.2/deps/v8/include/v8.h:878:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../srand.cc:32:3: error: no matching function for call to 'NODE_SET_METHOD'
  NODE_SET_METHOD(target, "random", Random);
  ^~~~~~~~~~~~~~~
/Users/redism/.node-gyp/1.0.2/src/node.h:212:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/redism/.node-gyp/1.0.2/src/node.h:200:13: note: candidate function [with TypeName = v8::Handle<v8::Object>] not viable:
      no known conversion from 'Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback' (aka 'void
      (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
../srand.cc:33:3: error: no matching function for call to 'NODE_SET_METHOD'
  NODE_SET_METHOD(target, "rand", Rand);
  ^~~~~~~~~~~~~~~
/Users/redism/.node-gyp/1.0.2/src/node.h:212:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/redism/.node-gyp/1.0.2/src/node.h:200:13: note: candidate function [with TypeName = v8::Handle<v8::Object>] not viable:
      no known conversion from 'Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback' (aka 'void
      (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
../srand.cc:34:3: error: no matching function for call to 'NODE_SET_METHOD'
  NODE_SET_METHOD(target, "srand", SRand);
  ^~~~~~~~~~~~~~~
/Users/redism/.node-gyp/1.0.2/src/node.h:212:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/redism/.node-gyp/1.0.2/src/node.h:200:13: note: candidate function [with TypeName = v8::Handle<v8::Object>] not viable:
      no known conversion from 'Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback' (aka 'void
      (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
../srand.cc:35:3: error: no matching function for call to 'NODE_SET_METHOD'
  NODE_SET_METHOD(target, "seed", SRand);
  ^~~~~~~~~~~~~~~
/Users/redism/.node-gyp/1.0.2/src/node.h:212:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/redism/.node-gyp/1.0.2/src/node.h:200:13: note: candidate function [with TypeName = v8::Handle<v8::Object>] not viable:
      no known conversion from 'Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback' (aka 'void
      (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
17 errors generated.
make: *** [Release/obj.target/srand/srand.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1038:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/redism/dev/sandbox/node-srand
gyp ERR! node -v v1.0.2
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v1.0.2
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE
npm ERR! srand@1.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the srand@1.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the srand package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls srand
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/redism/dev/sandbox/node-srand/npm-debug.log
```

**Comment by isaacs** [comment]
Yeah, it's been a while since I touched this thing.

I think the solution is to pull in https://github.com/rvagg/nan as a dep, and then use that.  If you send a patch, I'll give you this module, since you use it and I don't.

**Comment by suprememoocow** [comment]
Just a heads up that it's not compiling on node 0.12 for the same reason. 

I'm only using this module to seed very long, but predictable, sequences of numbers for testing purposes (with no security requirement), so I'm probably just going to switch to a simpler implementation, something like this: http://stackoverflow.com/a/19303725/50131

**Comment by redism** [comment]
Also there is pure javascript implementation with similar functionality. https://github.com/skratchdot/random-seed

**Comment by dortzur** [comment]
@isaacs there's a pending pull request from @dtaniwaki - will it be possible to merge?

**Comment by isaacs** [comment]
That PR doesn't build on node 4 or 5, as far as I can tell.

**Comment by dtaniwaki** [comment]
I fixed the PR just now. It seems I updated the code entirely. :)

**Comment by isaacs** [comment]
fixed, pushed, and published
